//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        public string CodeParking { get; set; }
        public string Quantity { get; set; }
        public string CodeCar { get; set; }
        public string IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
