//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltyDetail
    {
        public int IDPenaltyDetail { get; set; }
        public int IDPenalty { get; set; }
        public string Reason { get; set; }
        public decimal price { get; set; }
    
        public virtual Penalty Penalty { get; set; }
    }
}
