//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalDetail
    {
        public string IDRentalDetail { get; set; }
        public string IDRental { get; set; }
        public string LicensePlate { get; set; }
        public int RentalDays { get; set; }
        public decimal price { get; set; }
    
        public virtual Rental Rental { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
