//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VehicleData
    {
        public int IDVehicleType { get; set; }
        public string VehicleTypeName { get; set; }
        public string Color { get; set; }
        public string Status { get; set; }
        public string Manufacturer { get; set; }
        public int ManufactureYear { get; set; }
        public string Description { get; set; }
        public string LicensePlate { get; set; }
    }
}
