//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int IDWallet { get; set; }
        public int IDAcc { get; set; }
        public decimal Money { get; set; }
        public Nullable<System.DateTime> TradingDay { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public decimal Balance { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
